/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_argus_activex_ComException */

#ifndef _Included_com_argus_activex_ComException
#define _Included_com_argus_activex_ComException
#ifdef __cplusplus
extern "C" {
#endif
#undef com_argus_activex_ComException_serialVersionUID
#define com_argus_activex_ComException_serialVersionUID -3042686055658047285i64
#undef com_argus_activex_ComException_serialVersionUID
#define com_argus_activex_ComException_serialVersionUID -3387516993124229948i64
#undef com_argus_activex_ComException_serialVersionUID
#define com_argus_activex_ComException_serialVersionUID -7034897190745766939i64
#undef com_argus_activex_ComException_serialVersionUID
#define com_argus_activex_ComException_serialVersionUID -1273433102211257199i64
#ifdef __cplusplus
}
#endif
#endif
