/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_argus_activex_Dispatch */

#ifndef _Included_com_argus_activex_Dispatch
#define _Included_com_argus_activex_Dispatch
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: tlDispatch */
/* Inaccessible static: EMPTY_ARRAY */
/*
 * Class:     com_argus_activex_Dispatch
 * Method:    CreateObjectCOM
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_argus_activex_Dispatch_CreateObjectCOM
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_argus_activex_Dispatch
 * Method:    CreateObjectDCOM
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_argus_activex_Dispatch_CreateObjectDCOM
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_argus_activex_Dispatch
 * Method:    CreateObjectCanvas
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_argus_activex_Dispatch_CreateObjectCanvas
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_argus_activex_Dispatch
 * Method:    ReleaseObject
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_argus_activex_Dispatch_ReleaseObject
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Dispatch
 * Method:    AddListener
 * Signature: (ILjava/lang/String;Ljava/util/EventListener;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_argus_activex_Dispatch_AddListener
  (JNIEnv *, jobject, jint, jstring, jobject, jstring);

/*
 * Class:     com_argus_activex_Dispatch
 * Method:    RemoveListener
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Dispatch_RemoveListener
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_argus_activex_Dispatch
 * Method:    Invoke
 * Signature: (I[Lcom/argus/activex/Variant;ISLcom/argus/activex/Variant;)V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Dispatch_Invoke
  (JNIEnv *, jobject, jint, jobjectArray, jint, jshort, jobject);

/*
 * Class:     com_argus_activex_Dispatch
 * Method:    InvokeCLSID
 * Signature: (ILjava/lang/String;[Lcom/argus/activex/Variant;ISLcom/argus/activex/Variant;)V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Dispatch_InvokeCLSID
  (JNIEnv *, jobject, jint, jstring, jobjectArray, jint, jshort, jobject);

#ifdef __cplusplus
}
#endif
#endif
