/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_argus_activex_Variant */

#ifndef _Included_com_argus_activex_Variant
#define _Included_com_argus_activex_Variant
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: EMPTY_ARRAY */
/*
 * Class:     com_argus_activex_Variant
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_release
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_init
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    VariantClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_VariantClear
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    getvt
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_argus_activex_Variant_getvt
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    noParam
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_noParam
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    putEmpty
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_putEmpty
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    putBoolean
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_putBoolean
  (JNIEnv *, jobject, jboolean, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    putByte
 * Signature: (BZ)V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_putByte
  (JNIEnv *, jobject, jbyte, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    putShort
 * Signature: (SZ)V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_putShort
  (JNIEnv *, jobject, jshort, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    putInt
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_putInt
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    putCurrency
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_putCurrency
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    putFloat
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_putFloat
  (JNIEnv *, jobject, jfloat, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    putDouble
 * Signature: (DZ)V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_putDouble
  (JNIEnv *, jobject, jdouble, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    putDate
 * Signature: (DZ)V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_putDate
  (JNIEnv *, jobject, jdouble, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    putString
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_putString
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    putError
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_putError
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    putDispatch
 * Signature: (Lcom/argus/activex/Dispatch;Z)V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_putDispatch
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    getNull
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_getNull
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    getEmpty
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_Variant_getEmpty
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    getBoolean
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_argus_activex_Variant_getBoolean
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    getByte
 * Signature: (Z)B
 */
JNIEXPORT jbyte JNICALL Java_com_argus_activex_Variant_getByte
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    getShort
 * Signature: (Z)S
 */
JNIEXPORT jshort JNICALL Java_com_argus_activex_Variant_getShort
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    getInt
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_argus_activex_Variant_getInt
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    getCurrency
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_com_argus_activex_Variant_getCurrency
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    getFloat
 * Signature: (Z)F
 */
JNIEXPORT jfloat JNICALL Java_com_argus_activex_Variant_getFloat
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    getDouble
 * Signature: (Z)D
 */
JNIEXPORT jdouble JNICALL Java_com_argus_activex_Variant_getDouble
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    getDate
 * Signature: (Z)D
 */
JNIEXPORT jdouble JNICALL Java_com_argus_activex_Variant_getDate
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    getString
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_argus_activex_Variant_getString
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    getError
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_argus_activex_Variant_getError
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_argus_activex_Variant
 * Method:    isNull
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_argus_activex_Variant_isNull
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    toBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_argus_activex_Variant_toBoolean
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    toByte
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_argus_activex_Variant_toByte
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    toShort
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_argus_activex_Variant_toShort
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    toInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_argus_activex_Variant_toInt
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    toFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_argus_activex_Variant_toFloat
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    toDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_argus_activex_Variant_toDouble
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    toCurrency
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_argus_activex_Variant_toCurrency
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    toDate
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_argus_activex_Variant_toDate
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_argus_activex_Variant_toString
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    toError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_argus_activex_Variant_toError
  (JNIEnv *, jobject);

/*
 * Class:     com_argus_activex_Variant
 * Method:    toDispatch
 * Signature: ()Lcom/argus/activex/Dispatch;
 */
JNIEXPORT jobject JNICALL Java_com_argus_activex_Variant_toDispatch
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
