/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_argus_activex_TypeLib */

#ifndef _Included_com_argus_activex_TypeLib
#define _Included_com_argus_activex_TypeLib
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: LONG_NV */
/* Inaccessible static: INT_NV */
/* Inaccessible static: SHORT_NV */
/*
 * Class:     com_argus_activex_TypeLib
 * Method:    LoadTypeLib
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_argus_activex_TypeLib_LoadTypeLib
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_argus_activex_TypeLib
 * Method:    readData
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_argus_activex_TypeLib_readData
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
